# -*- coding: utf-8 -*-
"""JalNetra_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p5vww4m0gKwOqHpYumoU6K-IWoMquah2
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd

df = pd.read_csv("master_model_ready.csv")

print("Shape:", df.shape)
df.head()

import pandas as pd

df = pd.read_csv("master_model_ready.csv")

print("Shape:", df.shape)
df.head()

location_ids = df["location_id"]

X = df.drop(columns=["location_id", "flood_label"])
y = df["flood_label"]

print("Features:", X.shape)
print("Target:", y.shape)

print("\nTarget distribution:")
print(y.value_counts())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    stratify=y,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

print("\nTraining labels:")
print(y_train.value_counts())

print("\nTesting labels:")
print(y_test.value_counts())

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

model = Pipeline([
    ("scaler", StandardScaler()),
    ("classifier", LogisticRegression(random_state=42, max_iter=1000))
])

model.fit(X_train, y_train)

print("Model trained successfully!")

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

from sklearn.model_selection import StratifiedKFold, cross_val_score

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

cv_scores = cross_val_score(
    model,
    X,
    y,
    cv=cv,
    scoring="accuracy"
)

print("5-Fold CV Accuracy:")
print(cv_scores)

print("\nMean Accuracy:", cv_scores.mean())
print("Std Dev:", cv_scores.std())

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=4,
    random_state=42,
    class_weight="balanced"
)

rf_scores = cross_val_score(
    rf_model,
    X,
    y,
    cv=cv,
    scoring="accuracy"
)

print("Random Forest 5-Fold Accuracy:")
print(rf_scores)

print("\nMean Accuracy:", rf_scores.mean())
print("Std Dev:", rf_scores.std())

# Train Random Forest on the full dataset for feature importance
rf_model.fit(X, y)

feature_importance = pd.Series(
    rf_model.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

print(feature_importance)

from sklearn.model_selection import cross_val_score
from sklearn.metrics import make_scorer, roc_auc_score

logistic_auc = cross_val_score(
    model,
    X,
    y,
    cv=cv,
    scoring="roc_auc"
)

rf_auc = cross_val_score(
    rf_model,
    X,
    y,
    cv=cv,
    scoring="roc_auc"
)

print("Logistic Regression ROC-AUC:", logistic_auc)
print("Mean:", logistic_auc.mean())

print("\nRandom Forest ROC-AUC:", rf_auc)
print("Mean:", rf_auc.mean())

# Train final Logistic Regression on all available data
final_model = model.fit(X, y)

# Generate hotspot probability
risk_probability = final_model.predict_proba(X)[:, 1]

results = pd.DataFrame({
    "location_id": location_ids,
    "flood_label": y,
    "risk_score_pct": (risk_probability * 100).round(2),
    "predicted_class": final_model.predict(X)
})

results = results.sort_values("risk_score_pct", ascending=False)

print(results.to_string(index=False))

# Create presentation risk categories
def risk_category(score):
    if score >= 75:
        return "Very High"
    elif score >= 50:
        return "High"
    elif score >= 25:
        return "Moderate"
    else:
        return "Low"

results["risk_category"] = results["risk_score_pct"].apply(risk_category)

# Save final results
results.to_csv("floodlens_risk_scores.csv", index=False)

print(results.to_string(index=False))
print("\nSaved as: floodlens_risk_scores.csv")

# Add coordinates to the risk results
map_results = results.merge(
    df[["location_id", "latitude", "longitude"]],
    on="location_id",
    how="left"
)

# Put coordinates near the front
map_results = map_results[
    [
        "location_id",
        "latitude",
        "longitude",
        "risk_score_pct",
        "risk_category",
        "flood_label",
        "predicted_class"
    ]
]

# Save map-ready file
map_results.to_csv("floodlens_map_ready.csv", index=False)

print(map_results.to_string(index=False))
print("\nSaved as: floodlens_map_ready.csv")

import folium

# Center map on Gurugram
m = folium.Map(
    location=[map_results["latitude"].mean(), map_results["longitude"].mean()],
    zoom_start=12
)

# Risk colors
risk_colors = {
    "Very High": "red",
    "High": "orange",
    "Moderate": "yellow",
    "Low": "green"
}

# Add locations
for _, row in map_results.iterrows():
    folium.CircleMarker(
        location=[row["latitude"], row["longitude"]],
        radius=8,
        color=risk_colors[row["risk_category"]],
        fill=True,
        fill_color=risk_colors[row["risk_category"]],
        fill_opacity=0.75,
        popup=(
            f"<b>{row['location_id']}</b><br>"
            f"Risk Score: {row['risk_score_pct']}%<br>"
            f"Risk Category: {row['risk_category']}<br>"
            f"Known Hotspot Label: {row['flood_label']}"
        )
    ).add_to(m)

# Display
m

# Save the FloodLens map
m.save("floodlens_gurugram_risk_map.html")

print("Map saved successfully!")

import joblib

# Save trained model
joblib.dump(final_model, "floodlens_model.pkl")

# Save the exact feature order used by the model
joblib.dump(list(X.columns), "floodlens_feature_columns.pkl")

print("Model saved: floodlens_model.pkl")
print("Feature list saved: floodlens_feature_columns.pkl")

def predict_flood_risk(input_data):
    """
    input_data: dictionary containing the 24 model features
    """

    # Keep exactly the same feature order as training
    input_df = pd.DataFrame([input_data])[X.columns]

    probability = final_model.predict_proba(input_df)[0, 1]
    score = round(probability * 100, 2)

    if score >= 75:
        category = "Very High"
    elif score >= 50:
        category = "High"
    elif score >= 25:
        category = "Moderate"
    else:
        category = "Low"

    return {
        "risk_score_pct": score,
        "risk_category": category
    }

print("Prediction function ready!")

import joblib

loaded_model = joblib.load("floodlens_model.pkl")
loaded_features = joblib.load("floodlens_feature_columns.pkl")

print("Model loaded:", type(loaded_model).__name__)
print("Number of features:", len(loaded_features))
print("Features:", loaded_features)

# Test the independently loaded model on H01
test_row = df[df["location_id"] == "H01"].copy()

X_test_location = test_row[loaded_features]

probability = loaded_model.predict_proba(X_test_location)[0, 1]
prediction = loaded_model.predict(X_test_location)[0]

print("Location: H01")
print("Risk Score:", round(probability * 100, 2), "%")
print("Predicted Class:", prediction)

import zipfile

files_to_package = [
    "floodlens_model.pkl",
    "floodlens_feature_columns.pkl",
    "floodlens_map_ready.csv",
    "floodlens_risk_scores.csv",
    "floodlens_gurugram_risk_map.html"
]

with zipfile.ZipFile("FloodLens_model_package.zip", "w") as zipf:
    for file in files_to_package:
        zipf.write(file)

print("Package created: FloodLens_model_package.zip")

from google.colab import files
files.download("FloodLens_model_package.zip")

import zipfile
import os

with zipfile.ZipFile("FloodLens_model_package.zip", "r") as zip_ref:
    zip_ref.extractall("jalnetra_model")

print("Extracted files:")
print(os.listdir("jalnetra_model"))

import os
import time
from google.colab import output

os.system("pkill -f 'streamlit run app.py' || true")
time.sleep(2)

os.system(
    "streamlit run app.py "
    "--server.port 8501 "
    "--server.address 0.0.0.0 "
    "--server.enableCORS false "
    "--server.enableXsrfProtection false "
    "> streamlit.log 2>&1 &"
)

time.sleep(5)

url = output.eval_js("google.colab.kernel.proxyPort(8501)")
print("🌧️ JalNetra is LIVE!")
print(url)

from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, roc_auc_score

tuned_model = Pipeline([
    ("scaler", StandardScaler()),
    ("classifier", LogisticRegression(
        max_iter=5000,
        random_state=42
    ))
])

param_grid = {
    "classifier__C": [0.001, 0.01, 0.1, 0.5, 1, 2, 5, 10, 100],
    "classifier__penalty": ["l2"]
}

grid = GridSearchCV(
    tuned_model,
    param_grid,
    cv=5,
    scoring="accuracy"
)

grid.fit(X_train, y_train)

best_model = grid.best_estimator_

y_pred = best_model.predict(X_test)
y_prob = best_model.predict_proba(X_test)[:, 1]

print("Best Parameters:", grid.best_params_)
print("CV Accuracy:", round(grid.best_score_, 4))
print("Test Accuracy:", round(accuracy_score(y_test, y_pred), 4))
print("Test ROC-AUC:", round(roc_auc_score(y_test, y_prob), 4))

from sklearn.model_selection import StratifiedKFold, cross_val_predict
from sklearn.metrics import accuracy_score
import numpy as np

# Use the tuned model settings
threshold_model = Pipeline([
    ("scaler", StandardScaler()),
    ("classifier", LogisticRegression(
        C=grid.best_params_["classifier__C"],
        penalty="l2",
        max_iter=5000,
        random_state=42
    ))
])

# Get out-of-fold probabilities from TRAINING data only
cv_threshold = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

train_oof_prob = cross_val_predict(
    threshold_model,
    X_train,
    y_train,
    cv=cv_threshold,
    method="predict_proba"
)[:, 1]

# Find the best threshold using training data only
thresholds = np.arange(0.30, 0.71, 0.01)

threshold_results = []

for t in thresholds:
    pred = (train_oof_prob >= t).astype(int)
    acc = accuracy_score(y_train, pred)
    threshold_results.append((t, acc))

best_threshold, best_cv_acc = max(
    threshold_results,
    key=lambda x: x[1]
)

# Refit on all training data
threshold_model.fit(X_train, y_train)

# Evaluate ONCE on untouched test data
test_prob = threshold_model.predict_proba(X_test)[:, 1]
y_test_threshold_pred = (test_prob >= best_threshold).astype(int)

test_accuracy = accuracy_score(y_test, y_test_threshold_pred)

print("Best threshold:", round(best_threshold, 2))
print("Training CV accuracy at threshold:", round(best_cv_acc, 4))
print("Test accuracy:", round(test_accuracy, 4))

print("\nTest probabilities:")
for prob, actual, pred in zip(test_prob, y_test, y_test_threshold_pred):
    print(
        f"Actual={actual}  "
        f"Probability={prob:.3f}  "
        f"Prediction={pred}"
    )

# Remove geographic coordinates
X_no_geo = X.drop(columns=["latitude", "longitude"])

cv_no_geo = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

geo_removed_model = Pipeline([
    ("scaler", StandardScaler()),
    ("classifier", LogisticRegression(
        C=grid.best_params_["classifier__C"],
        penalty="l2",
        max_iter=5000,
        random_state=42
    ))
])

acc_no_geo = cross_val_score(
    geo_removed_model,
    X_no_geo,
    y,
    cv=cv_no_geo,
    scoring="accuracy"
)

auc_no_geo = cross_val_score(
    geo_removed_model,
    X_no_geo,
    y,
    cv=cv_no_geo,
    scoring="roc_auc"
)

print("Without latitude/longitude")
print("5-Fold Accuracy:", acc_no_geo)
print("Mean Accuracy:", round(acc_no_geo.mean(), 4))
print("Std Dev:", round(acc_no_geo.std(), 4))

print("\n5-Fold ROC-AUC:", auc_no_geo)
print("Mean ROC-AUC:", round(auc_no_geo.mean(), 4))

from sklearn.svm import SVC
from sklearn.ensemble import GradientBoostingClassifier

models = {
    "Logistic Regression": Pipeline([
        ("scaler", StandardScaler()),
        ("model", LogisticRegression(
            C=5,
            penalty="l2",
            max_iter=5000,
            random_state=42
        ))
    ]),

    "SVM": Pipeline([
        ("scaler", StandardScaler()),
        ("model", SVC(
            C=1,
            kernel="rbf",
            probability=True,
            random_state=42
        ))
    ]),

    "Gradient Boosting": GradientBoostingClassifier(
        n_estimators=100,
        learning_rate=0.03,
        max_depth=2,
        random_state=42
    )
}

for name, candidate in models.items():
    scores = cross_val_score(
        candidate,
        X_no_geo,
        y,
        cv=cv_no_geo,
        scoring="accuracy"
    )

    auc_scores = cross_val_score(
        candidate,
        X_no_geo,
        y,
        cv=cv_no_geo,
        scoring="roc_auc"
    )

    print(f"\n{name}")
    print("Accuracy:", scores)
    print("Mean Accuracy:", round(scores.mean(), 4))
    print("ROC-AUC:", round(auc_scores.mean(), 4))

from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

l1_model = Pipeline([
    ("scaler", StandardScaler()),
    ("classifier", LogisticRegression(
        penalty="l1",
        solver="liblinear",
        max_iter=5000,
        random_state=42
    ))
])

param_grid_l1 = {
    "classifier__C": [0.001, 0.01, 0.03, 0.05, 0.1, 0.3, 0.5, 1, 2, 5, 10]
}

grid_l1 = GridSearchCV(
    l1_model,
    param_grid_l1,
    cv=cv_no_geo,
    scoring="accuracy"
)

grid_l1.fit(X_no_geo, y)

print("Best L1 C:", grid_l1.best_params_)
print("Best CV Accuracy:", round(grid_l1.best_score_, 4))

# Show features retained by L1
coef = grid_l1.best_estimator_.named_steps["classifier"].coef_[0]

selected_features = [
    feature for feature, value in zip(X_no_geo.columns, coef)
    if abs(value) > 1e-8
]

print("\nSelected features:")
print(selected_features)
print("Number selected:", len(selected_features))

from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix

# Remove latitude/longitude from train and test
X_train_no_geo = X_train.drop(columns=["latitude", "longitude"])
X_test_no_geo = X_test.drop(columns=["latitude", "longitude"])

# L1 Logistic Regression
fair_l1_model = Pipeline([
    ("scaler", StandardScaler()),
    ("classifier", LogisticRegression(
        penalty="l1",
        solver="liblinear",
        max_iter=5000,
        random_state=42
    ))
])

l1_grid = GridSearchCV(
    fair_l1_model,
    {
        "classifier__C": [
            0.001, 0.01, 0.03, 0.05, 0.1,
            0.3, 0.5, 1, 2, 5, 10
        ]
    },
    cv=5,
    scoring="accuracy"
)

# IMPORTANT: fit only on training data
l1_grid.fit(X_train_no_geo, y_train)

best_l1 = l1_grid.best_estimator_

# Evaluate on untouched test set
test_pred = best_l1.predict(X_test_no_geo)
test_prob = best_l1.predict_proba(X_test_no_geo)[:, 1]

print("Best C:", l1_grid.best_params_["classifier__C"])
print("Training CV Accuracy:", round(l1_grid.best_score_, 4))
print("Test Accuracy:", round(accuracy_score(y_test, test_pred), 4))
print("Test ROC-AUC:", round(roc_auc_score(y_test, test_prob), 4))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, test_pred))

coef = best_l1.named_steps["classifier"].coef_[0]

selected = [
    feature
    for feature, value in zip(X_train_no_geo.columns, coef)
    if abs(value) > 1e-8
]

print("\nSelected Features:")
print(selected)

from sklearn.model_selection import RepeatedStratifiedKFold, cross_val_score

final_l1_cv_model = Pipeline([
    ("scaler", StandardScaler()),
    ("classifier", LogisticRegression(
        penalty="l1",
        solver="liblinear",
        C=2,
        max_iter=5000,
        random_state=42
    ))
])

X_model = X.drop(columns=["latitude", "longitude"])

repeated_cv = RepeatedStratifiedKFold(
    n_splits=5,
    n_repeats=10,
    random_state=42
)

acc_scores = cross_val_score(
    final_l1_cv_model,
    X_model,
    y,
    cv=repeated_cv,
    scoring="accuracy"
)

auc_scores = cross_val_score(
    final_l1_cv_model,
    X_model,
    y,
    cv=repeated_cv,
    scoring="roc_auc"
)

print("Repeated 5-Fold CV — 10 repeats")
print("Accuracy Mean:", round(acc_scores.mean(), 4))
print("Accuracy Std:", round(acc_scores.std(), 4))
print("Accuracy Min:", round(acc_scores.min(), 4))
print("Accuracy Max:", round(acc_scores.max(), 4))

print("\nROC-AUC Mean:", round(auc_scores.mean(), 4))
print("ROC-AUC Std:", round(auc_scores.std(), 4))

from sklearn.model_selection import RepeatedStratifiedKFold, cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

X_model = X.drop(columns=["latitude", "longitude"])

repeated_cv = RepeatedStratifiedKFold(
    n_splits=5,
    n_repeats=10,
    random_state=42
)

configs = [
    ("L1 C=0.1", "l1", 0.1),
    ("L1 C=0.3", "l1", 0.3),
    ("L1 C=0.5", "l1", 0.5),
    ("L1 C=1",   "l1", 1),
    ("L1 C=2",   "l1", 2),
    ("L1 C=5",   "l1", 5),
    ("L2 C=0.1", "l2", 0.1),
    ("L2 C=0.5", "l2", 0.5),
    ("L2 C=1",   "l2", 1),
    ("L2 C=2",   "l2", 2),
    ("L2 C=5",   "l2", 5),
]

results_compare = []

for name, penalty, C in configs:

    model_test = Pipeline([
        ("scaler", StandardScaler()),
        ("classifier", LogisticRegression(
            penalty=penalty,
            C=C,
            solver="liblinear",
            max_iter=5000,
            random_state=42
        ))
    ])

    acc = cross_val_score(
        model_test,
        X_model,
        y,
        cv=repeated_cv,
        scoring="accuracy"
    )

    auc = cross_val_score(
        model_test,
        X_model,
        y,
        cv=repeated_cv,
        scoring="roc_auc"
    )

    results_compare.append({
        "Model": name,
        "Accuracy": acc.mean(),
        "Accuracy_Std": acc.std(),
        "ROC_AUC": auc.mean()
    })

comparison_df = pd.DataFrame(results_compare).sort_values(
    "Accuracy",
    ascending=False
)

print(comparison_df.round(4).to_string(index=False))

import numpy as np

# Start from the non-geographic features
X_engineered = X.drop(columns=["latitude", "longitude"]).copy()

# Historical rainfall baselines
rain_hist_mean = (
    X_engineered["rainfall_2024_mm"] +
    X_engineered["rainfall_2025_mm"]
) / 2

hourly_hist_mean = (
    X_engineered["max_hourly_rainfall_2024_mm"] +
    X_engineered["max_hourly_rainfall_2025_mm"]
) / 2

# 1. 2026 rainfall anomaly vs previous two years
X_engineered["rainfall_2026_vs_history"] = (
    X_engineered["rainfall_2026_mm"] /
    rain_hist_mean.replace(0, np.nan)
).fillna(0)

# 2. 2026 peak-hour rainfall anomaly
X_engineered["hourly_2026_vs_history"] = (
    X_engineered["max_hourly_rainfall_2026_mm"] /
    hourly_hist_mean.replace(0, np.nan)
).fillna(0)

# 3. Natural flow balance
X_engineered["flow_balance"] = (
    X_engineered["natural_flow_out_flow"] -
    X_engineered["natural_flow_in_flow"]
)

# 4. Traffic delay fraction
X_engineered["traffic_delay_fraction"] = (
    X_engineered["traffic_delay_sec"] /
    X_engineered["normal_duration_sec"].replace(0, np.nan)
).fillna(0)

print("Original features:", X.shape[1])
print("Engineered features:", X_engineered.shape[1])

print("\nNew features:")
print([
    "rainfall_2026_vs_history",
    "hourly_2026_vs_history",
    "flow_balance",
    "traffic_delay_fraction"
])

from sklearn.model_selection import RepeatedStratifiedKFold, cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

engineered_model = Pipeline([
    ("scaler", StandardScaler()),
    ("classifier", LogisticRegression(
        penalty="l1",
        C=0.5,
        solver="liblinear",
        max_iter=5000,
        random_state=42
    ))
])

repeated_cv = RepeatedStratifiedKFold(
    n_splits=5,
    n_repeats=10,
    random_state=42
)

acc_engineered = cross_val_score(
    engineered_model,
    X_engineered,
    y,
    cv=repeated_cv,
    scoring="accuracy"
)

auc_engineered = cross_val_score(
    engineered_model,
    X_engineered,
    y,
    cv=repeated_cv,
    scoring="roc_auc"
)

print("Engineered Features — 5-Fold × 10 Repeats")
print("Accuracy Mean:", round(acc_engineered.mean(), 4))
print("Accuracy Std:", round(acc_engineered.std(), 4))
print("ROC-AUC Mean:", round(auc_engineered.mean(), 4))
print("ROC-AUC Std:", round(auc_engineered.std(), 4))

from sklearn.feature_selection import SelectKBest, f_classif

selection_results = []

for k in [5, 7, 9, 11, 13, 15, 18, 20]:

    selection_model = Pipeline([
        ("scaler", StandardScaler()),
        ("selector", SelectKBest(score_func=f_classif, k=k)),
        ("classifier", LogisticRegression(
            penalty="l2",
            C=1,
            max_iter=5000,
            random_state=42
        ))
    ])

    scores = cross_val_score(
        selection_model,
        X_model,
        y,
        cv=repeated_cv,
        scoring="accuracy"
    )

    auc = cross_val_score(
        selection_model,
        X_model,
        y,
        cv=repeated_cv,
        scoring="roc_auc"
    )

    selection_results.append({
        "k_features": k,
        "accuracy_mean": scores.mean(),
        "accuracy_std": scores.std(),
        "roc_auc_mean": auc.mean()
    })

selection_df = pd.DataFrame(selection_results)

print(selection_df.round(4).to_string(index=False))

# Remove traffic-level dummy variables
traffic_dummy_cols = [
    "traffic_level_High",
    "traffic_level_Moderate",
    "traffic_level_Severe"
]

X_no_traffic_dummies = X_model.drop(columns=traffic_dummy_cols)

traffic_clean_model = Pipeline([
    ("scaler", StandardScaler()),
    ("classifier", LogisticRegression(
        penalty="l1",
        C=0.5,
        solver="liblinear",
        max_iter=5000,
        random_state=42
    ))
])

clean_acc = cross_val_score(
    traffic_clean_model,
    X_no_traffic_dummies,
    y,
    cv=repeated_cv,
    scoring="accuracy"
)

clean_auc = cross_val_score(
    traffic_clean_model,
    X_no_traffic_dummies,
    y,
    cv=repeated_cv,
    scoring="roc_auc"
)

print("Without traffic-level dummy variables")
print("Accuracy Mean:", round(clean_acc.mean(), 4))
print("Accuracy Std:", round(clean_acc.std(), 4))
print("ROC-AUC Mean:", round(clean_auc.mean(), 4))
print("ROC-AUC Std:", round(clean_auc.std(), 4))

# Final JalNetra model
final_jalnetra_model = Pipeline([
    ("scaler", StandardScaler()),
    ("classifier", LogisticRegression(
        penalty="l1",
        C=0.5,
        solver="liblinear",
        max_iter=5000,
        random_state=42
    ))
])

# Use cleaned features:
# - no latitude/longitude
# - no traffic-level dummy variables
X_final = X_model.drop(columns=[
    "traffic_level_High",
    "traffic_level_Moderate",
    "traffic_level_Severe"
])

# Train on all 40 locations
final_jalnetra_model.fit(X_final, y)

# Save model + exact feature order
joblib.dump(final_jalnetra_model, "jalnetra_final_model.pkl")
joblib.dump(list(X_final.columns), "jalnetra_final_features.pkl")

print("✅ Final JalNetra model trained")
print("Features:", len(X_final.columns))
print("Saved:")
print("  jalnetra_final_model.pkl")
print("  jalnetra_final_features.pkl")

print("Final model features:")
print(X_final.columns.tolist())
print("\nNumber of features:", len(X_final.columns))

# Create two synthetic sample profiles from the real dataset:
# 1. Control-like profile = median of known control locations
# 2. Hotspot-like profile = median of known hotspot locations

control_profile = X_final[y == 0].median()
hotspot_profile = X_final[y == 1].median()

sample_inputs = pd.DataFrame([
    control_profile,
    hotspot_profile
], index=["Sample Control-like", "Sample Hotspot-like"])

# Predict using the final JalNetra model
sample_probabilities = final_jalnetra_model.predict_proba(sample_inputs)[:, 1]

for name, prob in zip(sample_inputs.index, sample_probabilities):
    score = round(prob * 100, 2)

    if score >= 75:
        category = "Very High"
    elif score >= 50:
        category = "High"
    elif score >= 25:
        category = "Moderate"
    else:
        category = "Low"

    print(f"{name}")
    print(f"Risk Score: {score}%")
    print(f"Risk Category: {category}")
    print("-" * 40)

# Manual sample: based on the observed feature ranges
manual_input = {
    "elevation_m": 220,
    "rainfall_2026_mm": 180,
    "max_hourly_rainfall_2026_mm": 45,
    "rainfall_2024_mm": 165,
    "max_hourly_rainfall_2024_mm": 42,
    "rainfall_2025_mm": 175,
    "max_hourly_rainfall_2025_mm": 44,
    "route_distance_m": 4200,
    "normal_duration_sec": 600,
    "traffic_duration_sec": 900,
    "traffic_delay_sec": 300,
    "congestion_ratio": 1.50,
    "traffic_avg_speed_kmh": 22,
    "distance_to_watershed_boundary_m": 350,
    "natural_flow_elevation": 215,
    "natural_flow_in_flow": 1.2,
    "natural_flow_out_flow": 0.7,
    "drain_area_sq_km": 0.8,
    "nearest_natural_flow_distance_m": 120
}

manual_df = pd.DataFrame([manual_input])[X_final.columns]

probability = final_jalnetra_model.predict_proba(manual_df)[0, 1]
score = round(probability * 100, 2)

if score >= 75:
    category = "Very High"
elif score >= 50:
    category = "High"
elif score >= 25:
    category = "Moderate"
else:
    category = "Low"

print("JalNetra Sample Prediction")
print("Risk Score:", score, "%")
print("Risk Category:", category)

from sklearn.model_selection import StratifiedKFold, cross_val_predict
from sklearn.metrics import accuracy_score

# Out-of-fold predictions for every real location
oof_cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

oof_model = Pipeline([
    ("scaler", StandardScaler()),
    ("classifier", LogisticRegression(
        penalty="l1",
        C=0.5,
        solver="liblinear",
        max_iter=5000,
        random_state=42
    ))
])

oof_prob = cross_val_predict(
    oof_model,
    X_final,
    y,
    cv=oof_cv,
    method="predict_proba"
)[:, 1]

oof_pred = (oof_prob >= 0.5).astype(int)

oof_results = pd.DataFrame({
    "location_id": df["location_id"],
    "actual": y.values,
    "risk_score_pct": (oof_prob * 100).round(2),
    "predicted": oof_pred
})

print("Out-of-fold accuracy:",
      round(accuracy_score(y, oof_pred), 4))

print("\nSample predictions:")
print(oof_results.sort_values("risk_score_pct", ascending=False).head(10).to_string(index=False))

# Train the final improved JalNetra model on all 40 locations

final_jalnetra_model = Pipeline([
    ("scaler", StandardScaler()),
    ("classifier", LogisticRegression(
        penalty="l1",
        C=0.5,
        solver="liblinear",
        max_iter=5000,
        random_state=42
    ))
])

# 19 final features:
# no latitude/longitude
# no traffic-level dummy variables
X_final = X_model.drop(columns=[
    "traffic_level_High",
    "traffic_level_Moderate",
    "traffic_level_Severe"
])

final_jalnetra_model.fit(X_final, y)

# Save exact model and feature order
joblib.dump(
    final_jalnetra_model,
    "jalnetra_final_model.pkl"
)

joblib.dump(
    list(X_final.columns),
    "jalnetra_final_features.pkl"
)

print("✅ Improved JalNetra model saved")
print("Features:", len(X_final.columns))
print("Cross-validated accuracy: ~78.25%")
print("Cross-validated ROC-AUC: ~87.25%")

# Generate updated JalNetra risk scores using the improved model

final_prob = final_jalnetra_model.predict_proba(X_final)[:, 1]
final_pred = final_jalnetra_model.predict(X_final)

updated_results = pd.DataFrame({
    "location_id": df["location_id"],
    "flood_label": y.values,
    "risk_score_pct": (final_prob * 100).round(2),
    "predicted_class": final_pred
})

def risk_category(score):
    if score >= 75:
        return "Very High"
    elif score >= 50:
        return "High"
    elif score >= 25:
        return "Moderate"
    else:
        return "Low"

updated_results["risk_category"] = (
    updated_results["risk_score_pct"].apply(risk_category)
)

updated_results = updated_results.sort_values(
    "risk_score_pct",
    ascending=False
)

updated_results.to_csv(
    "jalnetra_final_risk_scores.csv",
    index=False
)

print(updated_results.to_string(index=False))
print("\n✅ Saved: jalnetra_final_risk_scores.csv")

# Add coordinates to the NEW JalNetra risk scores

jalnetra_map = updated_results.merge(
    df[["location_id", "latitude", "longitude"]],
    on="location_id",
    how="left"
)

jalnetra_map = jalnetra_map[
    [
        "location_id",
        "latitude",
        "longitude",
        "risk_score_pct",
        "risk_category",
        "flood_label",
        "predicted_class"
    ]
]

jalnetra_map.to_csv(
    "jalnetra_final_map_ready.csv",
    index=False
)

print(jalnetra_map.to_string(index=False))
print("\n✅ Saved: jalnetra_final_map_ready.csv")

import folium
import zipfile
import os

# Create updated JalNetra map
m_final = folium.Map(
    location=[
        jalnetra_map["latitude"].mean(),
        jalnetra_map["longitude"].mean()
    ],
    zoom_start=12
)

risk_colors = {
    "Very High": "red",
    "High": "orange",
    "Moderate": "yellow",
    "Low": "green"
}

for _, row in jalnetra_map.iterrows():
    folium.CircleMarker(
        location=[row["latitude"], row["longitude"]],
        radius=8,
        color=risk_colors[row["risk_category"]],
        fill=True,
        fill_color=risk_colors[row["risk_category"]],
        fill_opacity=0.75,
        popup=(
            f"<b>{row['location_id']}</b><br>"
            f"Risk Score: {row['risk_score_pct']}%<br>"
            f"Risk Category: {row['risk_category']}<br>"
            f"Known Hotspot Label: {row['flood_label']}"
        )
    ).add_to(m_final)

m_final.save("jalnetra_final_map.html")

# Package improved model files
package_files = [
    "jalnetra_final_model.pkl",
    "jalnetra_final_features.pkl",
    "jalnetra_final_risk_scores.csv",
    "jalnetra_final_map_ready.csv",
    "jalnetra_final_map.html"
]

with zipfile.ZipFile("JalNetra_FINAL_PACKAGE.zip", "w") as z:
    for file in package_files:
        z.write(file)

print("✅ JalNetra final package created")
print("JalNetra_FINAL_PACKAGE.zip")

from google.colab import files
files.download("JalNetra_FINAL_PACKAGE.zip")

import pandas as pd

events = [
    # date, location/area, rainfall_mm, actual_waterlogging, match_type, source
    ["2024-06-28", "Sector 10A", 30.0, 1, "sector", "Social News XYZ"],
    ["2024-06-28", "Sector 31", 30.0, 1, "sector", "Social News XYZ"],
    ["2024-06-28", "Palam Vihar", 30.0, 1, "area", "Social News XYZ"],

    ["2024-07-04", "Palam Vihar", 35.5, 1, "area", "Hindustan Times"],

    ["2024-07-26", "Sector 57", 2.5, 1, "sector", "Hindustan Times"],

    ["2024-08-11", "Sector 15", 20.5, 1, "sector", "Times of India"],
    ["2024-08-11", "Sector 31", 20.5, 1, "sector", "Times of India"],

    ["2024-08-17", "Palam Vihar C Block", None, 1, "block", "Hindustan Times"],
    ["2024-08-17", "Palam Vihar D Block", None, 1, "block", "Hindustan Times"],

    ["2022-05-25", "Sector 15", None, 1, "sector", "India Today"],
    ["2022-05-25", "Sector 10", None, 1, "sector", "India Today"],
    ["2022-05-25", "Palam Vihar", None, 1, "area", "India Today"],

    ["2020-07-01", "Palam Vihar A Block", None, 1, "block", "Times of India"],
]

historical_events = pd.DataFrame(
    events,
    columns=[
        "event_date",
        "event_location",
        "rainfall_mm",
        "actual_waterlogging",
        "match_type",
        "source"
    ]
)

historical_events["event_date"] = pd.to_datetime(
    historical_events["event_date"]
)

historical_events.to_csv(
    "historical_flood_events.csv",
    index=False
)

print(historical_events)
print("\nSaved:", "historical_flood_events.csv")

import pandas as pd

# Load your files
events = pd.read_csv("historical_flood_events.csv")
locations = pd.read_csv("master_model_ready.csv")

# Your H locations only
H = locations[locations["location_id"].str.startswith("H")].copy()

# Add a clean name column for matching
# IMPORTANT: edit these names if your actual H01-H20 names differ
location_names = {
    "H01": "Sector 10A",
    "H02": "Sector 10A",
    "H03": "Sector 15 Part II",
    "H04": "Sector 15 Part II",
    "H05": "Sector 31",
    "H06": "Sector 46",
    "H07": "Sector 57",
    "H08": "Ghata",
    "H09": "Sector 57",
    "H10": "Silokhera",
    "H11": "Nathupur",
    "H12": "Nathupur",
    "H13": "Sikanderpur",
    "H14": "Sector 18",
    "H15": "Palam Vihar C Block",
    "H16": "Palam Vihar D Block",
    "H17": "Sector 23",
    "H18": "Sector 21",
    "H19": "Sector 22B",
    "H20": "Palam Vihar A Block"
}

H["location_name"] = H["location_id"].map(location_names)

# Show the locations before matching
print("YOUR H LOCATIONS:")
print(H[["location_id", "location_name", "latitude", "longitude"]].to_string(index=False))

# Show real historical events
print("\nREAL HISTORICAL EVENTS:")
print(events.to_string(index=False))

import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

# =========================
# 1. LOAD DATA
# =========================
data = pd.read_csv("master_model_ready.csv")
events = pd.read_csv("historical_flood_events.csv")

# =========================
# 2. TRAIN MODEL
# =========================
X = data.drop(columns=["location_id", "flood_label"])
y = data["flood_label"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

model = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    class_weight="balanced"
)

model.fit(X_train, y_train)

print("Model trained successfully.")

# =========================
# 3. MATCH REAL EVENTS
# =========================
location_names = {
    "H01": "Sector 10A",
    "H02": "Sector 10A",
    "H03": "Sector 15 Part II",
    "H04": "Sector 15 Part II",
    "H05": "Sector 31",
    "H06": "Sector 46",
    "H07": "Sector 57",
    "H08": "Ghata",
    "H09": "Sector 57",
    "H10": "Silokhera",
    "H11": "Nathupur",
    "H12": "Nathupur",
    "H13": "Sikanderpur",
    "H14": "Sector 18",
    "H15": "Palam Vihar C Block",
    "H16": "Palam Vihar D Block",
    "H17": "Sector 23",
    "H18": "Sector 21",
    "H19": "Sector 22B",
    "H20": "Palam Vihar A Block"
}

# Convert event names to the corresponding H locations
matches = []

for _, event in events.iterrows():

    name = event["event_location"]

    for location_id, location_name in location_names.items():

        # Exact/block match
        if name.lower() == location_name.lower():

            matches.append({
                "event_date": event["event_date"],
                "event_location": name,
                "location_id": location_id,
                "actual_waterlogging": event["actual_waterlogging"],
                "match_type": event["match_type"],
                "source": event["source"]
            })

        # Sector-level matching
        elif (
            event["match_type"] == "sector"
            and name.lower() == location_name.lower().replace(" part ii", "")
        ):
            matches.append({
                "event_date": event["event_date"],
                "event_location": name,
                "location_id": location_id,
                "actual_waterlogging": event["actual_waterlogging"],
                "match_type": "sector",
                "source": event["source"]
            })

matched_events = pd.DataFrame(matches)

# Remove duplicate matches
matched_events = matched_events.drop_duplicates(
    subset=["event_date", "event_location", "location_id"]
)

# =========================
# 4. PREDICT FOR MATCHED H LOCATIONS
# =========================
predictions = []

for location_id in matched_events["location_id"].unique():

    row = data[data["location_id"] == location_id]

    if len(row) == 0:
        continue

    X_location = row.drop(columns=["location_id", "flood_label"])

    prediction = model.predict(X_location)[0]
    probability = model.predict_proba(X_location)[0][1]

    predictions.append({
        "location_id": location_id,
        "model_prediction": int(prediction),
        "model_probability": round(probability, 3)
    })

predictions = pd.DataFrame(predictions)

# =========================
# 5. COMBINE ACTUAL + PREDICTION
# =========================
validation = matched_events.merge(
    predictions,
    on="location_id",
    how="left"
)

validation["correct"] = (
    validation["actual_waterlogging"]
    == validation["model_prediction"]
)

print("\n==============================")
print("REAL EVENT VALIDATION RESULTS")
print("==============================")

print(
    validation[
        [
            "event_date",
            "event_location",
            "location_id",
            "actual_waterlogging",
            "model_prediction",
            "model_probability",
            "correct",
            "source"
        ]
    ].to_string(index=False)
)

# =========================
# 6. SAVE RESULTS
# =========================
validation.to_csv(
    "real_historical_event_validation.csv",
    index=False
)

print("\nSaved: real_historical_event_validation.csv")

import os

files_to_delete = [
    "historical_flood_events.csv",
    "real_historical_event_validation.csv",
    "real_historical_event_predictions.csv"
]

for file in files_to_delete:
    if os.path.exists(file):
        os.remove(file)
        print("Deleted:", file)
    else:
        print("Not found:", file)

import pandas as pd

events = [
    ["2024-06-28", "Sector 10A", 30.0, 1, "sector", "Social News XYZ"],
    ["2024-06-28", "Sector 31", 30.0, 1, "sector", "Social News XYZ"],
    ["2024-06-28", "Palam Vihar", 30.0, 1, "area", "Social News XYZ"],
    ["2024-07-04", "Palam Vihar", 35.5, 1, "area", "Hindustan Times"],
    ["2024-07-26", "Sector 57", 2.5, 1, "sector", "Hindustan Times"],
    ["2024-08-11", "Sector 15", 20.5, 1, "sector", "Times of India"],
    ["2024-08-11", "Sector 31", 20.5, 1, "sector", "Times of India"],
    ["2024-08-17", "Palam Vihar C Block", None, 1, "block", "Hindustan Times"],
    ["2024-08-17", "Palam Vihar D Block", None, 1, "block", "Hindustan Times"],
    ["2022-05-25", "Sector 15", None, 1, "sector", "India Today"],
    ["2022-05-25", "Sector 10", None, 1, "sector", "India Today"],
    ["2022-05-25", "Palam Vihar", None, 1, "area", "India Today"],
    ["2020-07-01", "Palam Vihar A Block", None, 1, "block", "Times of India"],
]

events = pd.DataFrame(events, columns=[
    "event_date",
    "event_location",
    "rainfall_mm",
    "actual_waterlogging",
    "match_type",
    "source"
])

events.to_csv("historical_flood_events.csv", index=False)

print("Real historical event file recreated.")
print(events)

import pandas as pd

# Original model data
data = pd.read_csv("master_model_ready.csv")

# Real historical events
events = pd.read_csv("historical_flood_events.csv")

# H-location mapping
location_names = {
    "H01": "Sector 10A",
    "H02": "Sector 10A",
    "H03": "Sector 15 Part II",
    "H04": "Sector 15 Part II",
    "H05": "Sector 31",
    "H06": "Sector 46",
    "H07": "Sector 57",
    "H08": "Ghata",
    "H09": "Sector 57",
    "H10": "Silokhera",
    "H11": "Nathupur",
    "H12": "Nathupur",
    "H13": "Sikanderpur",
    "H14": "Sector 18",
    "H15": "Palam Vihar C Block",
    "H16": "Palam Vihar D Block",
    "H17": "Sector 23",
    "H18": "Sector 21",
    "H19": "Sector 22B",
    "H20": "Palam Vihar A Block"
}

# Match real events to H locations
matches = []

for _, event in events.iterrows():
    name = event["event_location"].lower()

    for location_id, location_name in location_names.items():
        lname = location_name.lower()

        if name == lname:
            matches.append({
                "event_date": event["event_date"],
                "event_location": event["event_location"],
                "location_id": location_id,
                "actual_waterlogging": event["actual_waterlogging"],
                "match_type": event["match_type"],
                "source": event["source"]
            })

        elif (
            event["match_type"] == "sector"
            and name == lname.replace(" part ii", "")
        ):
            matches.append({
                "event_date": event["event_date"],
                "event_location": event["event_location"],
                "location_id": location_id,
                "actual_waterlogging": event["actual_waterlogging"],
                "match_type": "sector",
                "source": event["source"]
            })

matched_events = pd.DataFrame(matches).drop_duplicates()

# ==========================================
# PREDICT USING EXISTING TRAINED MODEL
# ==========================================

results = []

for _, event in matched_events.iterrows():

    location_id = event["location_id"]

    row = data[data["location_id"] == location_id]

    if row.empty:
        continue

    X_location = row.drop(
        columns=["location_id", "flood_label"]
    )

    # EXISTING MODEL — NO TRAINING
    prediction = model.predict(X_location)[0]
    probability = model.predict_proba(X_location)[0][1]

    results.append({
        "event_date": event["event_date"],
        "event_location": event["event_location"],
        "location_id": location_id,
        "actual": int(event["actual_waterlogging"]),
        "predicted": int(prediction),
        "probability": round(probability, 3),
        "correct": int(
            event["actual_waterlogging"] == prediction
        ),
        "source": event["source"]
    })

results = pd.DataFrame(results)

print("\n======================================")
print("REAL EVENT vs EXISTING MODEL")
print("======================================\n")

print(results.to_string(index=False))

# Summary
correct = results["correct"].sum()
total = len(results)

print("\n======================================")
print(f"Correct: {correct}/{total}")
print(f"Accuracy: {correct/total:.2%}")
print("======================================")